version: '3'

services:
  api:
    container_name: todo_api
    build: ./api
    volumes:
      - ./api/src:/app/src
    tty: false
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - todo_api_network
      
  db:
    container_name: todo_api_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - type: volume
        source: mysql_todo_api_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    networks:
      - todo_api_network

volumes:
  mysql_todo_api_volume:
    name: mysql_todo_api_volume

networks:
  todo_api_network:
    external: false