name: Go CI

on:
  push:
    branches:
      - trial/ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: cd api/src
        run: go mod download

      - name: Generate mocks
        run: cd api/src
        run: go generate ./...

      - name: Run tests
        run: cd api/src
        run: go test -v ./...

